url: "https://remy.duthu.org"
baseurl: ""
title: "Rémy Duthu"
description: "Personal site of Rémy Duthu"

author:
  name: "Rémy Duthu"
  url: "https://remy.duthu.org"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: /assets/images/og/default.png

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false # Use Tailwind CSS JIT engine instead.
